const Works = [
    {
        id: 0,
        type: 'StandAndCandlestick',
        name: 'Подставка с подсвечником',
        discription: '',
        price: '15',
        icon: '', 
    },
    {
        id: 1,
        type: 'StandAndCandlestick',
        name: 'Подставка с подсвечником',
        discription: 'Нежная лаванда и золотая поталь',
        price: '15',
        icon: '', 
    },
    {
        id: 2,
        type: 'StandAndCandlestick',
        name: 'Подарочный набор',
        discription: 'Свеча соевая с деревянным фитилем и подставка. Набор выполнен из гипсобетона с лаковым покрытием.',
        price: '30',
        icon: '', 
    },

    {
        id: 0,
        type: 'StandAndCandlestick',
        name: 'Подарочный набор',
        discription: ' Подставка; Подставка круглая; Шкатулка. Исполнено в мраморной техники из высокопрочного гипсобетона с лаковым покрытием.',
        price: '25',
        icon: '', 
    },
    {
        id: 0,
        type: 'KashpoLilu',
        name: 'Кашпо Лилу',
        discription: 'Лавандовый обруч в горошек это волшебство какое-то',
        price: '58',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },{
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },

    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },
    {
        id: 0,
        type: '',
        name: '',
        discription: '',
        price: '',
        icon: '', 
    },

]